# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0017_resourcelist_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='error_details',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='error_summary',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
