# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0019_auto_20200417_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelabel',
            name='name',
            field=models.CharField(max_length=36),
        ),
    ]
