version: "3.2"
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: "ddmal/nginx:nightly"

  iipsrv:
    build:
      context: ./iipsrv
      dockerfile: Dockerfile
    image: "ddmal/iipsrv:nightly"
    
  rodan:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan:nightly"

  py3-celery:
    build:
      context: .
      dockerfile: ./python3-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan-python3-celery:nightly"

  gpu-celery:
    build:
      context: .
      dockerfile: ./gpu-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan-gpu-celery:nightly"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: "ddmal/postgres-plpython:nightly"

  rodan-client:
    build:
      context: ./rodan-client
      dockerfile: Dockerfile
    image: "ddmal/rodan-client:nightly"

  iipsrv:
    build:
      context: ./iipsrv
      dockerfile: Dockerfile
    image: "ddmal/iipsrv:nightly"
