version: "3.2"
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        VERSION: nightly
    image: "ghcr.io/ddmal/nginx:nightly"

  iipsrv:
    build:
      context: ./iipsrv
      dockerfile: Dockerfile
    image: "ghcr.io/ddmal/iipsrv:nightly"

  rodan:
    build:
      context: .
      dockerfile: rodan-main/Dockerfile
      args:
        BRANCHES: develop
        VERSION: nightly
    image: "ghcr.io/ddmal/rodan-main:nightly"

  py3-celery:
    build:
      context: .
      dockerfile: ./python3-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ghcr.io/ddmal/rodan-python3-celery:nightly"

  gpu-celery:
    build:
      context: .
      dockerfile: ./gpu-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ghcr.io/ddmal/rodan-gpu-celery:nightly"

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    image: "ghcr.io/ddmal/postgres-plpython:nightly"

  rodan-client:
    build:
      context: ./rodan-client
      dockerfile: Dockerfile
    image: "ghcr.io/ddmal/rodan-client:nightly"
