version: "3.2"
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: "ddmal/nginx:req"

  iipsrv:
    build:
      context: ./iipsrv
      dockerfile: Dockerfile
    image: "ddmal/iipsrv:nightly"

  rodan:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan:req"


  py3-celery:
    build:
      context: .
      dockerfile: ./python3-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan-python3-celery:req"

  gpu-celery:
    build:
      context: .
      dockerfile: ./gpu-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan-gpu-celery:req"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: "ddmal/postgres-plpython:req"

  rodan-client:
    build:
      context: ./rodan-client
      dockerfile: Dockerfile
    image: "ddmal/rodan-client:req"

  hpc-rabbitmq:
    build:
      context: ./hpc-rabbitmq
      dockerfile: Dockerfile
    image: "ddmal/hpc-rabbitmq:req"
