version: "3.2"
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: "ddmal/nginx:register_jobs"

  iipsrv:
    build:
      context: ./iipsrv
      dockerfile: Dockerfile
    image: "ddmal/iipsrv:nightly"
  rodan:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan:register_jobs"

  py3-celery:
    build:
      context: .
      dockerfile: ./python3-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan-python3-celery:register_jobs"

  gpu-celery:
    build:
      context: .
      dockerfile: ./gpu-celery/Dockerfile
      args:
        BRANCHES: develop
    image: "ddmal/rodan-gpu-celery:register_jobs"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    image: "ddmal/postgres-plpython:register_jobs"

  rodan-client:
    build:
      context: ./rodan-client
      dockerfile: Dockerfile
    image: "ddmal/rodan-client:register_jobs"

  hpc-rabbitmq:
    build:
      context: ./hpc-rabbitmq
      dockerfile: Dockerfile
    image: "ddmal/hpc-rabbitmq:register_jobs"
