#!/bin/bash

# Prompts user to select the server where files will be uploaded
echo "Please enter the number corresponding to the server you would like to upload to"
    select server in "rodan-dev.simssa.ca" "rodan.simssa.ca"; do
        case $server in
          rodan-dev.simssa.ca ) read -p "username: " username; read -p "password: " password; break;;
          rodan.simssa.ca ) read -p "username: " username; read -p "password: " password; break;;
        esac
    done

# Obtains and displays user token id
var=`curl -v -XPOST -d username=$username -d password=$password http://$server/auth/token/ | egrep '"token":"[^\, ]+' -o`
tokenid=${var:9:40}

# Obtains a list of projects uuid and asks user to input their choice of project 
curl -v -XGET -H "Authorization: Token $tokenid" http://$server/projects/ | egrep 'project/[^\/]+' -o 
echo "Please input the uuid of a project to which you would like to upload"
read projectid

# For N files in the directory where the script is located, N Post requests are created to upload all image files 
for file in *
do
    if [ "$file" = "mult_upload" ]; then
        continue
    fi
    curl -X POST -i -H "Authorization: Token $tokenid" -H "Accept: application/json" --form "files=@$file" --form "project=http://$server/project/$projectid/" http://$server/resources/
done # file

