apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rodan-resources
  namespace: rodan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2Ti
  volumeName: rodan-resources-pv