apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rodan-pg-data
  namespace: rodan
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: rodan-pg-data-pv