apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rodan-pg-backup
  namespace: rodan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: rodan-pg-backup-pv