# Generated by Django 2.0.13 on 2023-07-17 19:07

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0003_auto_20230627_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputport',
            name='extern_resources',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='rodan.Resource'),
        ),
    ]
