#!/bin/bash
# hooks/post_build

echo "[+] pose_build images with tag: $DOCKER_TAG"

# Pass testing a pull request
# Push to trigger webhook and send a message to slack
if [[ "$DOCKER_TAG" ==  "this" ]]; then
  docker tag ddmal/docker-webhook:placeholder ddmal/docker-webhook:rodan-pass-${SOURCE_BRANCH}-${DOCKER_TAG}
  docker push ddmal/docker-webhook:rodan-pass-${SOURCE_BRANCH}-${DOCKER_TAG}
fi
