#!/bin/bash
# hooks/post_checkout
# https://docs.docker.com/docker-cloud/builds/advanced/

# echo "[-] Changing branch"
# git checkout develop
# # git reset --hard HEAD
# # git clean -xffd
# # git pull origin develop

# echo "[-] Fetching tags"
# # git fetch --tags --quiet origin