#!/bin/bash
# hooks/post_push
# https://docs.docker.com/docker-cloud/builds/advanced/

RODAN_TAG='test'
#`cd rodan-main/code && git describe --tags --always`
RODAN_CLIENT_TAG='test'
#`cd rodan-client/code && git describe --tags --always`
RODAN_DOCKER_TAG='test'
#`git describe --tags --always`

# echo "[+] Pushing Python3-Celery"

# if [ -z `echo ${RODAN_TAG} | awk -F'-' '{print $3}'` ]; then
#   docker push ddmal/rodan-python3-celery:${RODAN_TAG}
# fi

# docker push ddmal/rodan-python3-celery:test

# echo "[+] Pushing GPU-Celery"

# if [ -z `echo ${RODAN_TAG} | awk -F'-' '{print $3}'` ]; then
#   docker push ddmal/rodan-gpu-celery:${RODAN_TAG}
# fi

# docker push ddmal/rodan-gpu-celery:test

echo "[+] Pushing Postgres"

if [ -z `echo ${RODAN_DOCKER_TAG} | awk -F'-' '{print $3}'` ]; then
  docker push ddmal/postgres-plpython:${RODAN_DOCKER_TAG}
fi

docker push ddmal/postgres-plpython:postgres_test

# echo "[+] Pushing Nginx"

# if [ -z `echo ${RODAN_DOCKER_TAG} | awk -F'-' '{print $3}'` ]; then
#   docker push ddmal/nginx:${RODAN_DOCKER_TAG}
# fi

# docker push ddmal/nginx:test

# echo "[+] Pushing HPC-RabbitMQ"

# if [ -z `echo ${RODAN_DOCKER_TAG} | awk -F'-' '{print $3}'` ]; then
#   docker push ddmal/hpc-rabbitmq:${RODAN_DOCKER_TAG}
# fi

# docker push ddmal/hpc-rabbitmq:test
