# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputport',
            options={'ordering': ['created'], 'permissions': (('view_inputport', 'View InputPort'),)},
        ),
        migrations.AlterModelOptions(
            name='outputport',
            options={'ordering': ['created'], 'permissions': (('view_outputport', 'View OutputPort'),)},
        ),
        migrations.AddField(
            model_name='inputport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outputport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
