# Generated by Django 2.0.13 on 2023-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0003_auto_20230627_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='ratio',
            field=models.FloatField(default=0.5),
        ),
    ]
