# Generated by Django 4.2.16 on 2026-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0005_auto_20230711_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='input',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inputport',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outputport',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resourcelist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resultspackage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='runjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tempauthtoken',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowjobgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowrun',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
