# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0016_auto_20190703_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelist',
            name='resource_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rodan.ResourceType'),
        ),
    ]
