# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0018_auto_20200318_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLabel',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='labels',
            field=models.ManyToManyField(blank=True, to='rodan.ResourceLabel'),
        ),
    ]
