# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 19:11
from __future__ import unicode_literals

from django.db import migrations, models

def classifier_to_noninteractive(apps, schema_editor):
    Job = apps.get_model('rodan', 'Job')
    for job in Job.objects.filter(name='Classifier'):
        job.name = 'Non-Interactive Classifier'
        job.save()

def noninteractive_to_classifier(apps, schema_editor):
    Job = apps.get_model('rodan', 'Job')
    for job in Job.objects.filter(name='Non-Interactive Classifier'):
        job.name = 'Classifier'
        job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0021_auto_20200429_0914'),
    ]

    operations = [
        migrations.RunPython(classifier_to_noninteractive, reverse_code=noninteractive_to_classifier)
    ]
