# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-15 23:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


def forwards_func(apps, schema_editor):
    """
    Auto-populate appearance data from coordinate data in coordinate set
    """
    db_alias = schema_editor.connection.alias

    wfj = apps.get_model("rodan", "WorkflowJob")
    wfj_cs = apps.get_model("rodan", "WorkflowJobCoordinateSet")
    wfjg = apps.get_model("rodan", "WorkflowJobGroup")
    wfjg_cs = apps.get_model("rodan", "WorkflowJobGroupCoordinateSet")

    # Django 2.2 has bulk_update, 1.11.29 does not.
    for i in wfj_cs.objects.using(db_alias):
      w = wfj.objects.filter(uuid=i.workflow_job.uuid).update(appearance=i.data)
    for i in wfjg_cs.objects.using(db_alias):
      w = wfjg.objects.filter(uuid=i.workflow_job_group.uuid).update(appearance=i.data)


class Migration(migrations.Migration):

    dependencies = [
        ('rodan', '0022_auto_20200817_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowjob',
            name='appearance',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowjobgroup',
            name='appearance',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='workflowjob',
            name='appearance',
            field=jsonfield.fields.JSONField(default={b'x': 0.5, b'y': 0.5}),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='workflowjobgroup',
            name='appearance',
            field=jsonfield.fields.JSONField(default={b'x': 0.5, b'y': 0.5}),
            preserve_default=True,
        ),
        migrations.DeleteModel(
            name='WorkflowJobCoordinateSet',
        ),
        migrations.DeleteModel(
            name='WorkflowJobGroupCoordinateSet',
        ),
    ]
