#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

echo "Creating local ssl certificates."

# 2048 is ok for Local. Production should be 4096
openssl dhparam -out ./nginx/certs/dhparam.pem 2048

openssl req -x509 \
  -newkey rsa:4096 \
  -out ./nginx/certs/cert.pem \
  -keyout ./nginx/certs/key.pem \
  -days 3650 \
  -nodes \
  -subj '/C=CA/ST=Quebec/L=Montreal/O=McGillUniversity/OU=DDMAL/CN=localhost'

echo "Done."
