#!/bin/sh
echo
echo "############################"
echo "started installing python3 jobs"
echo "############################"
echo
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

cd /code/Rodan/rodan/jobs

PIP=$(which pip3) || PIP=:

# update pip
$PIP install -U pip

# Install pil_rodan
# pil_rodan is required for Calvo-Classifier because of the jpeg2000 resource type.
$PIP install -r ./py3_requirements.txt


# GAMERA 4 INSTALLATION
echo
echo "############################"
echo "started installing gamera 4"
echo "############################"
echo
cd /

# clone the gamera-4 repository and install it on the container 
git clone https://github.com/hsnr-gamera/gamera-4.git
cd ./gamera-4

git checkout 1b62614d9f3500f61b9bdae13f8f0788d7ccf48b #using this particular commit for now
python3 setup.py --nowx build && python3 setup.py --nowx install

# remove the gamera-4 directory from the container. 
cd / && rm -rf gamera-4

# for more information and if any errors refer to: Rodan/rodan-main/code/rodan/jobs/gamera_rodan/gamera-rodan-doc.md

# At the end, add all the jobs together.
cd /code/Rodan/rodan

sed -i 's/#py3 //g' /code/Rodan/rodan/settings.py