#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

cd /code/Rodan/rodan/jobs

PIP=$(which pip3) || PIP=$(which pip)

# Install Calvo-classifier
$PIP install -r ./Calvo_classifier/requirements.txt
mkdir ~/.keras && cd ~/.keras; touch ./keras.json || echo "[+] Could not make a .keras directory. Does it already exist?"
# Force build

cat << EOF | python3
new_backend = """{
    "image_dim_ordering": "tf",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "tensorflow"
}"""
open("keras.json", "w").write(new_backend)
EOF

cd /code/Rodan/rodan/jobs
# Install Text Alignment
$PIP install -r ./text_alignment/requirements.txt

#Needed for django installation (seems to be needed in gpu container only)
$PIP install typing_extensions==4.2.0

cd /code/Rodan/rodan
sed -i 's/#gpu //g' /code/Rodan/rodan/settings.py
