#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

# Install tools made with Gamera
cd /code
git clone https://github.com/DDMAL/document-preprocessing-toolkit.git
cd document-preprocessing-toolkit/
pip install ./background-estimation ./border-removal ./new_binarization_toolkit ./stable_paths_toolkit ./staffline-removal >/dev/null
pip install ./lyric-extraction >/dev/null
pip install svn+svn://svn.code.sf.net/p/music-staves/code/ >/dev/null
cd /code
git clone https://github.com/DDMAL/rodan_plugins.git
pip install /code/rodan_plugins >/dev/null

