#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

# cd /code/Rodan
# chgrp -R www-data *
# chown -R www-data:www-data /rodan/data/

# Install Django(Rodan) python packages.
pip install -r /code/Rodan/requirements.txt

# pybagit/bagit.py needs to be executable.
# After successfully installing the package you can uncomment the following line to make it work 
# chmod -R 755 /usr/local/lib/python2.7/dist-packages/pybagit || chmod -R 755 /src/pybagit/pybagit


# Register all the job types added by install_jobs.sh.
cd /code/Rodan/rodan
ln -s /code/jobs/* /code/Rodan/rodan/jobs || echo "Running again to be certain that all jobs are linked correctly"
