#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

cd /code/Rodan/rodan/jobs

# Install Calvo-Trainer-HPC
pip install -r ./hpc_fast_trainer/requirements.txt >/dev/null



cd /code/Rodan/rodan
# At the end, add all the jobs together.
sed -i 's/#py2 //g' /code/Rodan/rodan/settings.py
