#!/bin/bash
set -o errexit # Exit immediately if a command exits with a non-zero status.
set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

chmod -R a+rwx /var

_term() { 
  echo "Caught SIGTERM signal!" 
  kill -TERM "$child_2" 2>/dev/null
}

trap _term SIGTERM

cd /code/Rodan

# Wait until other services are up before going up
/run/wait-for-app postgres:5432
/run/wait-for-app redis:6379
/run/wait-for-app rodan-main:8000 --timeout=900

runuser -u www-data -- celery worker -A rodan --workdir /code/Rodan -Q ${CELERY_JOB_QUEUE} --concurrency=10 -n "${CELERY_JOB_QUEUE}" -l INFO --logfile /code/Rodan/rodan-celery-${CELERY_JOB_QUEUE}.log &
child_2=$!
wait "$child_2"
