#!/bin/sh
set -o errexit # Exit immediately if a command exits with a non-zero status.
# set -o nounset # Treat unset variables as an error when substituting.
set -o xtrace # Print commands and their arguments as they are executed.

chmod -R 777 /code/Rodan/
cd /code/Rodan
runuser -u www-data -- yes | MIGRATE="True" python manage.py migrate --noinput

chown www-data /code/Rodan/database.log /code/Rodan/rodan.log

# This is just a fancy way to create a superuser account automatically if one is
# not present. The credentials for this user are defined in the environment
# variables file in the Rodan-Docker project. This version of django requires the white
# spaces you see here. https://github.com/DDMAL/rodan-docker/issues/2
cat << EOF | runuser -u www-data -- python manage.py shell

import os
from django.contrib.auth.models import User
print ("Checking if Django super user exists...")
if not User.objects.filter(username=os.getenv('ADMIN_USER')).exists():
    User.objects.create_superuser(os.getenv('ADMIN_USER'), '', os.getenv('ADMIN_PASS'))
    print ("Created new user.")

EOF

mkdir /code/Rodan/rodan/static || echo "Static directory already exists!"


runuser -u www-data -- python manage.py collectstatic --noinput
# Stop the token expiry, because the entire token authentication is very broken and this is a fix until
# we can decouple djoser and reconstruct the token auth the right way.
sed -i "s/15/999999/g" /code/Rodan/rodan/settings.py
# This serves rodan to nginx, it could also be a unix socket.
# [TODO] Test to see if it is any faster to use unix sockets instead of http requests between containers.
# Usually, unix sockets would be faster but between docker containers, I am not certain because of the
# complexity from volumes. Do not merge other services into the rodan service. We are keeping them isolated
# for scaling in the future. --graceful-timeout 0 --preload True --workers=3
runuser -u www-data -- /usr/local/bin/gunicorn --name=rodan -b 0.0.0.0:8000 --max-requests 10000 --worker-connections 1001 --log-level=debug --log-file=/code/Rodan/gunicorn-error.log --access-logfile=/code/Rodan/gunicorn-access.log rodan.wsgi_django:application
