server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.17.170:3100/loki/api/v1/push

scrape_configs:
- job_name: rodan_celery
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: SERVER_HOST
      __path__: /code/Rodan/*.log