# This workflow will lint the project using flake8 and run tests.

name: Biollante Rodan Job
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install Gamera
      run: |
        git clone https://github.com/hsnr-gamera/gamera.git ./gamera
        cd gamera
        # Checkout version used in Rodan
        git reset --hard c77194d5e839204efc617971233967ba5a6c53bc
        python setup.py install --nowx
        cd ..
        rm -rf gamera
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --statistics
    - name: Run tests
      run: |
        python -m unittest knnga_util_test
